[workspace]
members = [
    "crates/resp",
    "crates/nimbis",
    "crates/telemetry",
    "crates/storage",
    "crates/config",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["marsevilspirit <marsevilspirit@gmail.com>"]
license = "MIT"
repository = "https://github.com/marsevilspirit/nimbis"

[workspace.dependencies]
resp = { path = "crates/resp" }
telemetry = { path = "crates/telemetry" }
storage = { path = "crates/storage" }
config = { path = "crates/config" }

bytes = "1.5"
thiserror = "2.0.17"
tokio = { version = "1.35", features = ["full"] }
criterion = { version = "0.8.1", features = ["html_reports"] }
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-appender = "0.2"
slatedb = "0.9.2"
object_store = "0.13.0"
rstest = "0.26.1"
ulid = "1.2"
arc-swap = "1.8.0"
smart-default = "0.7.1"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
